import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Game | Ping Pong",
  description: "Generated by create next app",
};

export default function GameLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      {children}
    </section>
  );
}
